package STP.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 24 11:51:19 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContratorEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ContractorId,
        LocationId,
        ContractorTypeId,
        ContractorName,
        Cnic,
        ContactNo,
        Active,
        EnteredBy,
        EnteredOn,
        LastEditedBy,
        LastEditedOn,
        ContractorTypeEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CONTRACTORID = AttributesEnum.ContractorId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int CONTRACTORTYPEID = AttributesEnum.ContractorTypeId.index();
    public static final int CONTRACTORNAME = AttributesEnum.ContractorName.index();
    public static final int CNIC = AttributesEnum.Cnic.index();
    public static final int CONTACTNO = AttributesEnum.ContactNo.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int ENTEREDBY = AttributesEnum.EnteredBy.index();
    public static final int ENTEREDON = AttributesEnum.EnteredOn.index();
    public static final int LASTEDITEDBY = AttributesEnum.LastEditedBy.index();
    public static final int LASTEDITEDON = AttributesEnum.LastEditedOn.index();
    public static final int CONTRACTORTYPEEO = AttributesEnum.ContractorTypeEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ContratorEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("STP.model.eo.ContratorEO");
    }


    /**
     * Gets the attribute value for ContractorId, using the alias name ContractorId.
     * @return the value of ContractorId
     */
    public Number getContractorId() {
        return (Number) getAttributeInternal(CONTRACTORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractorId.
     * @param value value to set the ContractorId
     */
    public void setContractorId(Number value) {
        setAttributeInternal(CONTRACTORID, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the value of LocationId
     */
    public Number getLocationId() {
        return (Number) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(Number value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for ContractorTypeId, using the alias name ContractorTypeId.
     * @return the value of ContractorTypeId
     */
    public Number getContractorTypeId() {
        return (Number) getAttributeInternal(CONTRACTORTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractorTypeId.
     * @param value value to set the ContractorTypeId
     */
    public void setContractorTypeId(Number value) {
        setAttributeInternal(CONTRACTORTYPEID, value);
    }

    /**
     * Gets the attribute value for ContractorName, using the alias name ContractorName.
     * @return the value of ContractorName
     */
    public String getContractorName() {
        return (String) getAttributeInternal(CONTRACTORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractorName.
     * @param value value to set the ContractorName
     */
    public void setContractorName(String value) {
        setAttributeInternal(CONTRACTORNAME, value);
    }

    /**
     * Gets the attribute value for Cnic, using the alias name Cnic.
     * @return the value of Cnic
     */
    public String getCnic() {
        return (String) getAttributeInternal(CNIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cnic.
     * @param value value to set the Cnic
     */
    public void setCnic(String value) {
        setAttributeInternal(CNIC, value);
    }

    /**
     * Gets the attribute value for ContactNo, using the alias name ContactNo.
     * @return the value of ContactNo
     */
    public String getContactNo() {
        return (String) getAttributeInternal(CONTACTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactNo.
     * @param value value to set the ContactNo
     */
    public void setContactNo(String value) {
        setAttributeInternal(CONTACTNO, value);
    }

    /**
     * Gets the attribute value for Active, using the alias name Active.
     * @return the value of Active
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Active.
     * @param value value to set the Active
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for EnteredBy, using the alias name EnteredBy.
     * @return the value of EnteredBy
     */
    public Number getEnteredBy() {
        return (Number) getAttributeInternal(ENTEREDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnteredBy.
     * @param value value to set the EnteredBy
     */
    public void setEnteredBy(Number value) {
        setAttributeInternal(ENTEREDBY, value);
    }

    /**
     * Gets the attribute value for EnteredOn, using the alias name EnteredOn.
     * @return the value of EnteredOn
     */
    public Date getEnteredOn() {
        return (Date) getAttributeInternal(ENTEREDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnteredOn.
     * @param value value to set the EnteredOn
     */
    public void setEnteredOn(Date value) {
        setAttributeInternal(ENTEREDON, value);
    }

    /**
     * Gets the attribute value for LastEditedBy, using the alias name LastEditedBy.
     * @return the value of LastEditedBy
     */
    public Number getLastEditedBy() {
        return (Number) getAttributeInternal(LASTEDITEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastEditedBy.
     * @param value value to set the LastEditedBy
     */
    public void setLastEditedBy(Number value) {
        setAttributeInternal(LASTEDITEDBY, value);
    }

    /**
     * Gets the attribute value for LastEditedOn, using the alias name LastEditedOn.
     * @return the value of LastEditedOn
     */
    public Date getLastEditedOn() {
        return (Date) getAttributeInternal(LASTEDITEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastEditedOn.
     * @param value value to set the LastEditedOn
     */
    public void setLastEditedOn(Date value) {
        setAttributeInternal(LASTEDITEDON, value);
    }

    /**
     * @return the associated entity ContractorTypeEOImpl.
     */
    public ContractorTypeEOImpl getContractorTypeEO() {
        return (ContractorTypeEOImpl) getAttributeInternal(CONTRACTORTYPEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity ContractorTypeEOImpl.
     */
    public void setContractorTypeEO(ContractorTypeEOImpl value) {
        setAttributeInternal(CONTRACTORTYPEEO, value);
    }


    /**
     * @param contractorId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number contractorId) {
        return new Key(new Object[] { contractorId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        SequenceImpl seq = new SequenceImpl("CONTRACTOR_S", getDBTransaction());
        setContractorId(seq.getSequenceNumber());

        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

