package STP.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 15 16:18:36 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FabDetailEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        FabDetId,
        FabId,
        ItemId,
        Percentage,
        Remarks,
        EnteredBy,
        EnteredOn,
        LastEditedBy,
        LastEditedOn,
        FabMasterEO,
        ItemMasterEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FABDETID = AttributesEnum.FabDetId.index();
    public static final int FABID = AttributesEnum.FabId.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int PERCENTAGE = AttributesEnum.Percentage.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ENTEREDBY = AttributesEnum.EnteredBy.index();
    public static final int ENTEREDON = AttributesEnum.EnteredOn.index();
    public static final int LASTEDITEDBY = AttributesEnum.LastEditedBy.index();
    public static final int LASTEDITEDON = AttributesEnum.LastEditedOn.index();
    public static final int FABMASTEREO = AttributesEnum.FabMasterEO.index();
    public static final int ITEMMASTEREO = AttributesEnum.ItemMasterEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FabDetailEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("STP.model.eo.FabDetailEO");
    }


    /**
     * Gets the attribute value for FabDetId, using the alias name FabDetId.
     * @return the value of FabDetId
     */
    public Number getFabDetId() {
        return (Number) getAttributeInternal(FABDETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabDetId.
     * @param value value to set the FabDetId
     */
    public void setFabDetId(Number value) {
        setAttributeInternal(FABDETID, value);
    }

    /**
     * Gets the attribute value for FabId, using the alias name FabId.
     * @return the value of FabId
     */
    public Number getFabId() {
        return (Number) getAttributeInternal(FABID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabId.
     * @param value value to set the FabId
     */
    public void setFabId(Number value) {
        setAttributeInternal(FABID, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the value of ItemId
     */
    public Number getItemId() {
        return (Number) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for Percentage, using the alias name Percentage.
     * @return the value of Percentage
     */
    public Number getPercentage() {
        return (Number) getAttributeInternal(PERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Percentage.
     * @param value value to set the Percentage
     */
    public void setPercentage(Number value) {
        setAttributeInternal(PERCENTAGE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for EnteredBy, using the alias name EnteredBy.
     * @return the value of EnteredBy
     */
    public Number getEnteredBy() {
        return (Number) getAttributeInternal(ENTEREDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnteredBy.
     * @param value value to set the EnteredBy
     */
    public void setEnteredBy(Number value) {
        setAttributeInternal(ENTEREDBY, value);
    }

    /**
     * Gets the attribute value for EnteredOn, using the alias name EnteredOn.
     * @return the value of EnteredOn
     */
    public Date getEnteredOn() {
        return (Date) getAttributeInternal(ENTEREDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnteredOn.
     * @param value value to set the EnteredOn
     */
    public void setEnteredOn(Date value) {
        setAttributeInternal(ENTEREDON, value);
    }

    /**
     * Gets the attribute value for LastEditedBy, using the alias name LastEditedBy.
     * @return the value of LastEditedBy
     */
    public Number getLastEditedBy() {
        return (Number) getAttributeInternal(LASTEDITEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastEditedBy.
     * @param value value to set the LastEditedBy
     */
    public void setLastEditedBy(Number value) {
        setAttributeInternal(LASTEDITEDBY, value);
    }

    /**
     * Gets the attribute value for LastEditedOn, using the alias name LastEditedOn.
     * @return the value of LastEditedOn
     */
    public Date getLastEditedOn() {
        return (Date) getAttributeInternal(LASTEDITEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastEditedOn.
     * @param value value to set the LastEditedOn
     */
    public void setLastEditedOn(Date value) {
        setAttributeInternal(LASTEDITEDON, value);
    }

    /**
     * @return the associated entity FabMasterEOImpl.
     */
    public FabMasterEOImpl getFabMasterEO() {
        return (FabMasterEOImpl) getAttributeInternal(FABMASTEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity FabMasterEOImpl.
     */
    public void setFabMasterEO(FabMasterEOImpl value) {
        setAttributeInternal(FABMASTEREO, value);
    }

    /**
     * @return the associated entity ItemMasterEOImpl.
     */
    public ItemMasterEOImpl getItemMasterEO() {
        return (ItemMasterEOImpl) getAttributeInternal(ITEMMASTEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity ItemMasterEOImpl.
     */
    public void setItemMasterEO(ItemMasterEOImpl value) {
        setAttributeInternal(ITEMMASTEREO, value);
    }


    /**
     * @param fabDetId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number fabDetId) {
        return new Key(new Object[] { fabDetId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("FAB_DETAIL_S", getDBTransaction());
        setFabDetId(seq.getSequenceNumber());

    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

